#!/bin/bash

set -Eeuxo pipefail

# INSTALL QEMU-SYSTEM
if [ ! "$(which /usr/bin/qemu-system-x86_64)" ]; then
  sudo apt install --no-install-suggests --no-install-recommends ovmf qemu-system-x86 qemu-system-gui -y
fi

# ENVIRONMET VARIABLE
MACHINE_NAME="Debian-12"
QEMU_ROOT_DIR="/$(realpath --relative-to=/ $(dirname $0))/Resources"
QEMU_IMG="$QEMU_ROOT_DIR/disk.img"
SSH_PORT="5555"
OVMF_CODE="/usr/share/OVMF/OVMF_CODE_4M.ms.fd"
OVMF_VARS_ORIG="/usr/share/OVMF/OVMF_VARS_4M.ms.fd"
OVMF_VARS="$QEMU_ROOT_DIR/bios"

[ ! -d $QEMU_ROOT_DIR ] && mkdir -pv $QEMU_ROOT_DIR

if [ ! -e "${QEMU_IMG}" ]; then
  sudo apt install --no-install-suggests --no-install-recommends qemu-utils -y
  qemu-img create -f qcow2 "${QEMU_IMG}" 100G
fi

if [[ ! -e "${OVMF_VARS}" ]]; then
  cp -rfv "${OVMF_VARS_ORIG}" "${OVMF_VARS}"
fi

qemu-system-x86_64 \
  -enable-kvm \
  -machine q35,smm=on \
  -cpu host -smp $(nproc) -m 4096 \
  -object rng-random,filename=/dev/urandom,id=rng0 \
  -boot order=c,menu=on \
  -device virtio-rng-pci,rng=rng0 \
  -name "${MACHINE_NAME}" \
  -net nic,model=virtio \
  -net user,hostfwd=tcp::${SSH_PORT}-:22 \
  -vga virtio \
  -global driver=cfi.pflash01,property=secure,value=on \
  -drive if=pflash,format=raw,unit=0,file="${OVMF_CODE}",readonly=on \
  -drive if=pflash,format=raw,unit=1,file="${OVMF_VARS}" \
  -drive file="${QEMU_IMG}",format=qcow2 \
  -virtfs local,path=/media/xxx,mount_tag=shared_folder,security_model=passthrough,id=shared_folder \
  -device intel-hda -device hda-duplex \
  -monitor stdio \
  $@

  #-cpu host -smp cores=4,threads=1 -m 4096 \
  #-drive file=/dev/sdd,format=raw,media=disk \
  #-cdrom /media/xxx/HGST-EXFAT/Bootable/debian-live-12.4.0-amd64-gnome.iso \

  # REQUIRED ROOT ACCESS
  #-drive file=/dev/sda,format=raw
  #-drive file=/dev/sdd,format=raw,media=disk

  #-usb
  #-device usb-host,hostbus=3,hostaddr=3 \

  # SOUND
  #-device intel-hda -device hda-duplex \

  # SOUND WITH STREAM
  #-audiodev pa,id=pa,server=unix:${XDG_RUNTIME_DIR}/pulse/native,out.stream-name=foobar,in.stream-name=foobar -device intel-hda -device hda-duplex,audiodev=pa,mixer=off \

  # SHARED FOLDER
  # mount -t 9p shared_folder /mnt/shared_folder --mkdir
  #-virtfs local,path=/tmp,mount_tag=shared_folder,security_model=passthrough,id=shared_folder \
